version: '3.8'

services:
  api:
    build: .
    container_name: uptimerobot-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    stdin_open: true
    tty: true